# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    # set "concurrent_simulators" to false to avoid "Caught error... 65"
    # https://github.com/fastlane/fastlane/issues/14201
    capture_screenshots(workspace: "SleepoLingo.xcworkspace", scheme: "SleepoLingoUITests", concurrent_simulators: false)
    frame_screenshots
    # upload_to_app_store
  end

  lane :icons do
  appicon(
    appicon_devices: [:ipad, :iphone, :ios_marketing],
    appicon_path: "SleepoLingo/Images.xcassets"
  )
  end
end
